### ISSUE TITLE
A NoMethodError occurred in help#unhappy

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/reklamacijenet-theme#2]
I.e. http://reklamacije.net/help/unhappy/REQUEST_SLUG

A NoMethodError occurred in help#unhappy:

undefined method `show_response_no_followup_path' for #<#:0x0000000e71b048>
lib/themes/reklamacijenet-theme/lib/views/help/unhappy.html.erb:46:in `_lib_themes_reklamacijenet_theme_lib_views_help_unhappy_html_erb___407606147317672545_121224820'

...

-------------------------------
Backtrace:
-------------------------------

lib/themes/reklamacijenet-theme/lib/views/help/unhappy.html.erb:46:in `_lib_themes_reklamacijenet_theme_lib_views_help_unhappy_html_erb___407606147317672545_121224820'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'

[ERROR] [reklamacije.net] help#unhappy (NoMethodError) "undefined method `show_response_no_followup_path' for #<#<Class:... 
https://codeforcroatia.helpmonks.com/mailbox/57136beb759fe9ee16f418f9/inbox/5a15e134cfa16823d57d73dd

**Comment by schlos** [comment]
Fixed and deployed to LIVE
